name: Build FFmpeg-Kit for Android

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ffmpeg-kit:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 hours timeout for long builds
    
    # No matrix needed since we're building all architectures in one job
    # but will disable all except arm64-v8a
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c
        add-to-path: false
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          wget \
          curl \
          git \
          cmake \
          ninja-build \
          pkg-config \
          autoconf \
          automake \
          libtool \
          make \
          yasm \
          nasm \
          python3 \
          python3-pip \
          unzip \
          zip \
          tar \
          gzip \
          bzip2 \
          xz-utils \
          file
          
    - name: Set up environment variables
      run: |
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "ANDROID_NDK_ROOT=$ANDROID_NDK_ROOT" >> $GITHUB_ENV
        echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "PATH=$PATH:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_ENV
        
    - name: Verify Android setup
      run: |
        echo "Android SDK Root: $ANDROID_SDK_ROOT"
        echo "Android NDK Root: $ANDROID_NDK_ROOT"
        ls -la $ANDROID_SDK_ROOT/
        ls -la $ANDROID_NDK_ROOT/
        
    - name: Clone FFmpeg-Kit repository
      run: |
        git clone https://github.com/arthenica/ffmpeg-kit.git
        cd ffmpeg-kit
        git submodule update --init --recursive
        
    - name: Cache build dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ffmpeg-kit/android/src/main/cpp/external-libraries
        key: ${{ runner.os }}-ffmpeg-kit-${{ hashFiles('ffmpeg-kit/android.sh') }}
        restore-keys: |
          ${{ runner.os }}-ffmpeg-kit-
          
    - name: Prepare build script with custom options
      run: |
        cd ffmpeg-kit
        
        # Create a build script that only uses supported ffmpeg-kit options
        cat > custom_android_build.sh << 'EOF'
        #!/bin/bash
        
        # Set strict error handling
        set -e
        
        # Export required environment variables
        export ANDROID_SDK_ROOT="$ANDROID_SDK_ROOT"
        export ANDROID_NDK_ROOT="$ANDROID_NDK_ROOT"
        export ANDROID_HOME="$ANDROID_SDK_ROOT"
        
        # Architecture disable options (disable all except arm64-v8a)
        ARCH_OPTIONS="--disable-arm-v7a \
        --disable-arm-v7a-neon \
        --disable-x86 \
        --disable-x86-64"
        
        echo "Building FFmpeg-Kit for arm64-v8a only"
        echo "Disabled architectures: armeabi-v7a, armeabi-v7a-neon, x86, x86_64"
        echo "Note: Some libraries (gnutls, libssh, libzmq, librtmp, librist, libsmbclient) are not available in ffmpeg-kit"
        echo "Building with full set of available libraries and GPL support"
        
        # Run the build with only supported options
        ./android.sh \
          --full \
          --enable-gpl \
          $ARCH_OPTIONS
        
        EOF
        
        chmod +x custom_android_build.sh
        
    - name: Build FFmpeg-Kit for arm64-v8a only
      run: |
        cd ffmpeg-kit
        ./custom_android_build.sh
        
    - name: Verify build output
      run: |
        cd ffmpeg-kit
        echo "Build completed for arm64-v8a"
        echo "Checking prebuilt directory:"
        ls -la prebuilt/
        
        if [ -d "prebuilt/android-arm64-v8a" ]; then
          echo "Contents of prebuilt/android-arm64-v8a:"
          ls -la "prebuilt/android-arm64-v8a/"
        fi
        
        # Check for AAR files
        find . -name "*.aar" -type f | head -10
        
        # Check for SO files
        find . -name "*.so" -type f | head -10
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-kit-arm64-v8a
        path: |
          ffmpeg-kit/prebuilt/android-arm64-v8a/
          ffmpeg-kit/android/ffmpeg-kit-android-lib/build/outputs/aar/
        retention-days: 30
        
    - name: Upload build logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs-arm64-v8a
        path: |
          ffmpeg-kit/build.log
          ffmpeg-kit/android/build/
        retention-days: 7

  # Job to package the arm64-v8a build
  package-build:
    runs-on: ubuntu-latest
    needs: build-ffmpeg-kit
    if: always() && (needs.build-ffmpeg-kit.result == 'success')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts/
        
    - name: Package arm64-v8a build
      run: |
        mkdir -p packaged-build/
        
        # Copy arm64-v8a build to packaged directory
        if [ -d "artifacts/ffmpeg-kit-arm64-v8a" ]; then
          echo "Packaging arm64-v8a build"
          cp -r "artifacts/ffmpeg-kit-arm64-v8a"/* packaged-build/ || true
        fi
        
        echo "Packaged build contents:"
        ls -la packaged-build/
        
    - name: Upload packaged build
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-kit-arm64-v8a-only
        path: packaged-build/
        retention-days: 90
        
    - name: Create release summary
      run: |
        echo "# FFmpeg-Kit Android Build Summary" > build-summary.md
        echo "" >> build-summary.md
        echo "## Build Configuration" >> build-summary.md
        echo "- **Target ABIs**: arm64-v8a only (all other ABIs disabled as requested)" >> build-summary.md
        echo "- **Disabled Libraries**: Note - gnutls, libssh, libzmq, librtmp, librist, libsmbclient are not available in ffmpeg-kit" >> build-summary.md
        echo "- **Disabled Components**: Note - protocols, network, specific input/output devices not directly controllable in ffmpeg-kit" >> build-summary.md
        echo "- **Enabled Options**: GPL, full build with all available ffmpeg-kit libraries" >> build-summary.md
        echo "" >> build-summary.md
        echo "## Artifacts" >> build-summary.md
        echo "- Individual ABI builds: ffmpeg-kit-{abi-name}" >> build-summary.md
        echo "- Combined build: ffmpeg-kit-android-all-abis" >> build-summary.md
        echo "" >> build-summary.md
        echo "Built on: $(date)" >> build-summary.md
        
    - name: Upload build summary
      uses: actions/upload-artifact@v4
      with:
        name: build-summary
        path: build-summary.md
